"""
============================================================
  Student Attendance System — Flask Backend
  File: app.py
  Author: Generated by Antigravity
  Description:
      A production-ready Flask API that integrates with the
      Google Sheets API (via gspread + oauth2client) to read
      student data and write attendance records into the
      spreadsheet "Registration 2nd Sem (1)".

  Spreadsheet Layout (assumed):
      Row 1  : Title/Banner text
      Row 2  : Headers → A="S.NO.", B="Roll No.", C="Reg Number",
                          D="Name", E…="Dates", LAST="Percentage"
      Row 3+ : Student data rows

  Smart-Write Logic:
      On POST /api/attendance the backend:
        1. Scans Row 2 to locate the "Percentage" column index.
        2. Inserts a brand-new column immediately BEFORE it.
        3. Writes today's date (M/D/YYYY) in Row 2 of the new column.
        4. Matches each incoming student Roll No / Reg Number and
           writes "P" or "A" in the corresponding row of the new col.
============================================================
"""
import os
import json
import logging
import sys
from datetime import datetime
from typing import Any

import gspread
from flask import Flask, jsonify, render_template, request
from oauth2client.service_account import ServiceAccountCredentials

# ---------------------------------------------------------------------------
# Logging Configuration
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger("attendance_system")

# ---------------------------------------------------------------------------
# Flask Application Initialisation
# ---------------------------------------------------------------------------
app = Flask(__name__)

# ---------------------------------------------------------------------------
# Google Sheets Configuration
# ---------------------------------------------------------------------------
# Spreadsheet ID from the Google Sheets URL.
# URL format: https://docs.google.com/spreadsheets/d/<SPREADSHEET_ID>/edit
SPREADSHEET_ID = "1f2XM7HFk0IYSiOyKYEKkNMd3j-lB6NgLS0qlh5M3o0M"

# Worksheet GID (the number after #gid= in the browser URL). 0 = first sheet.
WORKSHEET_GID = 0

# OAuth 2.0 scope grants: Sheets read/write + Drive read (needed by gspread).
SCOPES = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive.file",
    "https://www.googleapis.com/auth/drive",
]

# Path to the downloaded Service Account JSON key (must be in project root).
CREDENTIALS_FILE = "credentials.json"

# ---------------------------------------------------------------------------
# Sheet layout constants  (1-based row / column indexing)
# ---------------------------------------------------------------------------
# New sheet structure (Discrete Mathematics):
#   Rows 1-6  : empty / title area
#   Row  7    : Headers → A=S NO, B=Roll NO, C=Reg NO, D=Student Name,
#                          E=Present, F=Absent, G=Percentage, H+=dates
#   Row  8+   : Student data
HEADER_ROW     = 7   # row that holds column labels
DATA_START_ROW = 8   # first row with student data

# Date columns start after the fixed columns (H = column 8).
DATE_COL_START = 8   # 1-based index of first possible date column

# Fixed column positions (1-based)
SERIAL_COL = 1   # A → S NO
ROLL_COL   = 2   # B → Roll NO
REG_COL    = 3   # C → Reg NO
NAME_COL   = 4   # D → Student Name
# E=Present, F=Absent, G=Percentage are formula/count cols — not written by app


# ---------------------------------------------------------------------------
# Helpers: Google Sheets authentication & worksheet access
# ---------------------------------------------------------------------------

def _get_gspread_client() -> gspread.Client:
    """
    Authenticates with Google APIs using the Service Account credentials
    stored in CREDENTIALS_FILE and returns an authorised gspread client.
    Raises a RuntimeError if the credentials file is missing or invalid.
    """
    try:
        creds = ServiceAccountCredentials.from_json_keyfile_name(
            CREDENTIALS_FILE, SCOPES
        )
        client = gspread.authorize(creds)
        logger.info("Successfully authenticated with Google Sheets API.")
        return client
    except FileNotFoundError:
        msg = (
            f"'{CREDENTIALS_FILE}' not found. Place your downloaded Service "
            "Account JSON key in the project root and rename it 'credentials.json'."
        )
        logger.error(msg)
        raise RuntimeError(msg)
    except Exception as exc:
        logger.exception("Failed to authenticate with Google Sheets API.")
        raise RuntimeError(f"Authentication error: {exc}") from exc


def _open_worksheet() -> gspread.Worksheet:
    """
    Opens the target spreadsheet by its ID (no Drive API needed) and returns
    the correct Worksheet object using the GID from the browser URL.
    """
    client = _get_gspread_client()
    try:
        spreadsheet = client.open_by_key(SPREADSHEET_ID)
        if WORKSHEET_GID is not None:
            # Find the worksheet whose id matches the GID in the URL
            worksheet = next(
                (ws for ws in spreadsheet.worksheets() if ws.id == WORKSHEET_GID),
                None,
            )
            if worksheet is None:
                raise RuntimeError(
                    f"No worksheet with GID {WORKSHEET_GID} found in spreadsheet {SPREADSHEET_ID}. "
                    "Check the #gid= value in your Google Sheets URL."
                )
        else:
            worksheet = spreadsheet.sheet1
        logger.info(
            "Opened worksheet '%s' (GID: %s) from spreadsheet ID '%s'.",
            worksheet.title,
            worksheet.id,
            SPREADSHEET_ID,
        )
        return worksheet
    except gspread.SpreadsheetNotFound:
        msg = (
            f"Spreadsheet ID '{SPREADSHEET_ID}' not found. "
            "Ensure the sheet has been shared with the service account email: "
            "attendance-bot@striker-auction.iam.gserviceaccount.com"
        )
        logger.error(msg)
        raise RuntimeError(msg)


# ---------------------------------------------------------------------------
# Helpers: Column scanning utilities
# ---------------------------------------------------------------------------

def _find_col_index(header_row_values: list[str], label: str) -> int | None:
    """
    Returns the 1-based column index for a given label within a header row list.
    Returns None if the label is not found.
    """
    for idx, cell_value in enumerate(header_row_values, start=1):
        if cell_value.strip() == label.strip():
            return idx
    return None


def _col_index_to_letter(col_index: int) -> str:
    """
    Converts a 1-based column index to its A1-notation letter(s).
    e.g. 1 → 'A', 26 → 'Z', 27 → 'AA'
    """
    result = ""
    while col_index > 0:
        col_index, remainder = divmod(col_index - 1, 26)
        result = chr(65 + remainder) + result
    return result


# Common date formats that may appear in a Google Sheet cell.
# strptime's %d / %m accept both zero-padded and non-padded values,
# so "%d/%m/%Y" matches both "18/07/2026" and "18/7/2026".
_DATE_FORMATS = [
    "%d/%m/%Y",   # 18/07/2026  (DD/MM/YYYY — new sheet format)
    "%m/%d/%Y",   # 07/18/2026  (M/D/YYYY  — old sheet format)
    "%Y-%m-%d",   # 2026-07-18
    "%d-%m-%Y",   # 18-07-2026
    "%Y/%m/%d",   # 2026/07/18
    "%d.%m.%Y",   # 18.07.2026
]


def _parse_date_cell(cell_value: str) -> datetime | None:
    """
    Attempts to parse a date string from a sheet cell into a datetime object.
    Tries multiple common formats so format variations don't cause mismatches.
    Returns None if the string cannot be parsed as any known date format.
    """
    v = cell_value.strip()
    if not v:
        return None
    for fmt in _DATE_FORMATS:
        try:
            return datetime.strptime(v, fmt)
        except ValueError:
            continue
    return None


# ---------------------------------------------------------------------------
# API Endpoint: GET /api/students
# ---------------------------------------------------------------------------

@app.route("/api/students", methods=["GET"])
def get_students() -> Any:
    """
    Reads all student records from the spreadsheet (Row 3 downwards) and
    returns a JSON array. Each element has the shape:
        { "roll_no": "...", "reg_no": "...", "name": "..." }

    Only rows that have at least a Roll No value are included; empty trailing
    rows are automatically skipped.
    """
    try:
        worksheet = _open_worksheet()

        # Fetch all values in the sheet once (single API call).
        all_values: list[list[str]] = worksheet.get_all_values()

        if len(all_values) < DATA_START_ROW:
            logger.warning("Sheet has fewer than %d rows — no student data.", DATA_START_ROW)
            return jsonify({"students": [], "count": 0})

        students = []
        for row_idx, row in enumerate(all_values[DATA_START_ROW - 1 :], start=DATA_START_ROW):
            # Pad short rows to avoid IndexError
            while len(row) < NAME_COL:
                row.append("")

            roll_no = row[ROLL_COL - 1].strip()
            reg_no  = row[REG_COL - 1].strip()
            name    = row[NAME_COL - 1].strip()

            # Skip entirely empty rows (trailing sheet rows)
            if not roll_no and not reg_no and not name:
                continue

            students.append(
                {
                    "roll_no": roll_no,
                    "reg_no":  reg_no,
                    "name":    name,
                }
            )

        logger.info("Fetched %d student records.", len(students))
        return jsonify({"students": students, "count": len(students)})

    except RuntimeError as exc:
        logger.error("GET /api/students failed: %s", exc)
        return jsonify({"error": str(exc)}), 500
    except Exception as exc:
        logger.exception("Unexpected error in GET /api/students.")
        return jsonify({"error": f"An unexpected error occurred: {exc}"}), 500


# ---------------------------------------------------------------------------
# API Endpoint: POST /api/attendance
# ---------------------------------------------------------------------------

@app.route("/api/attendance", methods=["POST"])
def submit_attendance() -> Any:
    """
    Accepts attendance data and writes it into the sheet.

    Target-Column Logic:
        1. Reads Row DATA_START_ROW (first student data row).
        2. Scans from column DATE_COL_START (H) rightward.
        3. The FIRST column that has no 'P' or 'A' in that row is the target.
        4. Writes the selected date as the header in HEADER_ROW of that column.
        5. Writes P/A for every student in that column (skips non-empty cells).
        6. Expands the sheet grid automatically if the column exceeds grid limits.
    """
    # ── 1. Parse & validate ───────────────────────────────────────────────────
    payload: dict = request.get_json(silent=True) or {}
    attendance_records: list[dict] = payload.get("attendance", [])
    selected_date: str = payload.get("date", "").strip()

    if not attendance_records:
        return jsonify({"error": "No attendance records provided."}), 400
    if not selected_date:
        return jsonify({"error": "No date selected. Please pick a date before submitting."}), 400

    # Convert YYYY-MM-DD → DD/MM/YYYY for the sheet header
    try:
        parsed_date = datetime.strptime(selected_date, "%Y-%m-%d")
        date_str = parsed_date.strftime("%d/%m/%Y")   # e.g. "18/07/2026"
    except ValueError:
        return jsonify({"error": f"Invalid date: '{selected_date}'. Expected YYYY-MM-DD."}), 400

    try:
        worksheet = _open_worksheet()

        # ── 2. Fetch entire sheet once ────────────────────────────────────────
        all_values: list[list[str]] = worksheet.get_all_values()

        if len(all_values) < DATA_START_ROW:
            return jsonify({"error": f"Sheet has fewer than {DATA_START_ROW} rows."}), 400

        # ── 3. Find target column by scanning the FIRST DATA ROW ─────────────
        # Read Row DATA_START_ROW (0-indexed: DATA_START_ROW - 1).
        # Start from DATE_COL_START (column H = index 7 in 0-based).
        # The first column whose cell is NOT 'P' / 'A' is our write target.
        first_data_row: list[str] = all_values[DATA_START_ROW - 1]

        target_col_idx: int | None = None
        col_scan = DATE_COL_START  # start from column H (1-based)
        while True:
            cell_0 = col_scan - 1   # 0-based index
            current_val = (
                first_data_row[cell_0].strip().upper()
                if cell_0 < len(first_data_row)
                else ""
            )
            if current_val not in ("P", "A"):
                target_col_idx = col_scan
                break
            col_scan += 1
            # Safety: stop at column 200 to prevent infinite loop
            if col_scan > 200:
                return jsonify({"error": "Could not find an empty attendance column (scanned up to column 200)."}), 500

        target_col_letter = _col_index_to_letter(target_col_idx)
        logger.info(
            "First empty attendance column: %d (%s).",
            target_col_idx, target_col_letter,
        )

        # ── 4. Expand sheet grid if needed ────────────────────────────────────
        if target_col_idx > worksheet.col_count:
            new_total = target_col_idx + 10
            worksheet.resize(cols=new_total)
            logger.info("Sheet grid expanded to %d columns.", new_total)

        # ── 5. Write the selected date into the header row ────────────────────
        date_cell = f"{target_col_letter}{HEADER_ROW}"
        worksheet.update_acell(date_cell, date_str)
        logger.info("Wrote date header '%s' to %s.", date_str, date_cell)

        # ── 6. Build student row-number lookup ────────────────────────────────
        row_lookup: dict[str, int] = {}   # roll → sheet row
        reg_lookup: dict[str, int] = {}   # reg  → sheet row

        for row_idx, row in enumerate(all_values[DATA_START_ROW - 1:], start=DATA_START_ROW):
            while len(row) < NAME_COL:
                row.append("")
            roll = row[ROLL_COL - 1].strip()
            reg  = row[REG_COL  - 1].strip()
            if roll:
                row_lookup[roll] = row_idx
            if reg:
                reg_lookup[reg] = row_idx

        # ── 7. Read current column values (to skip already-filled cells) ──────
        col_current: list[str] = worksheet.col_values(target_col_idx)

        # ── 8. Build batch update list ────────────────────────────────────────
        cells_to_update = []
        matched_count   = 0
        skipped_count   = 0
        unmatched_rolls = []

        for record in attendance_records:
            roll   = record.get("roll_no", "").strip()
            reg    = record.get("reg_no",  "").strip()
            status = record.get("status",  "A").strip().upper()
            if status not in ("P", "A"):
                status = "A"

            sheet_row = row_lookup.get(roll) or reg_lookup.get(reg)
            if sheet_row is None:
                logger.warning("No match for Roll='%s' / Reg='%s'.", roll, reg)
                unmatched_rolls.append(roll or reg)
                continue

            # Skip if this cell already has P or A
            existing = (
                col_current[sheet_row - 1].strip().upper()
                if sheet_row <= len(col_current) else ""
            )
            if existing in ("P", "A"):
                skipped_count += 1
                continue

            row_num, col_num = gspread.utils.a1_to_rowcol(
                f"{target_col_letter}{sheet_row}"
            )
            cells_to_update.append(gspread.Cell(row=row_num, col=col_num, value=status))
            matched_count += 1

        # ── 9. Single batch write ─────────────────────────────────────────────
        if cells_to_update:
            worksheet.update_cells(cells_to_update, value_input_option="USER_ENTERED")
            logger.info(
                "Wrote %d cells to col %s (skipped %d already-filled).",
                matched_count, target_col_letter, skipped_count,
            )

        # ── 10. Return summary ────────────────────────────────────────────────
        response = {
            "success":         True,
            "date_written":    date_str,
            "column_written":  target_col_letter,
            "is_new_column":   True,
            "matched_count":   matched_count,
            "skipped_count":   skipped_count,
            "total_submitted": len(attendance_records),
            "unmatched":       unmatched_rolls,
        }
        logger.info("Attendance done: %s", json.dumps(response))
        return jsonify(response), 200

    except RuntimeError as exc:
        logger.error("POST /api/attendance failed: %s", exc)
        return jsonify({"error": str(exc)}), 500
    except Exception as exc:
        logger.exception("Unexpected error in POST /api/attendance.")
        return jsonify({"error": f"An unexpected server error occurred: {exc}"}), 500





# ---------------------------------------------------------------------------
# Root Route — serves the frontend HTML dashboard
# ---------------------------------------------------------------------------

@app.route("/")
def index():
    """Serves the main attendance dashboard."""
    return render_template("index.html")


# ---------------------------------------------------------------------------
# Application Entry Point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    logger.info("Starting Student Attendance System…")
    logger.info("Open your browser at: http://127.0.0.1:5000")
    # debug=True enables hot-reload during development.
    # Set debug=False for production deployments.
    app.run(host="127.0.0.1", port=5000, debug=True)
